Algoritmo "lista2 exercicio1C slide"
//  
//  
// Disciplina   : LPOO
// Professor   : Aldo Henrique
// Autor(a)    : Rafael Sampaio Tibery Silva
// Data atual  : -----
Var
num: inteiro
Inicio
escreva("digite um numero")
leia(num)
        se (num mod 2=0) entao
           escreva ("o numero é par")
        fimse
                   se (num mod 2=1) entao
                      escreva ("o numero é impar")
                   fimse
Fimalgoritmo
